### ISSUE TITLE
EntityListeners' callback methods are not executed in the order the classes are specified in the annotation

### ISSUE THREAD

**Issue by delocalizer** [mhgrove/Empire#111]
I have an entity class annotated as follows:
<pre>
@EntityListeners({
    LabelValidator.class,
    ModifiedStamp.class,
    CollectionCheck.class
})
</pre>

If each of LabelValidator, ModifiedStamp and CollectionCheck have for example a @PreUpdate annotated method I expect that before update the methods be executed in the order defined by the classes in the annotation, based on JPA 1.0 spec (2.0 & 2.1 the same text) : 

ejb-3_0-fr-spec-persistence.pdf
<pre>
3.5.4 Multiple Lifecycle Callback Methods for an Entity Lifecycle Event
....
"The lifecycle callback methods defined on the entity listener classes for an entity class or mapped superclass
are invoked in the same order as the specification of the entity listener classes in the EntityListeners
annotation."
</pre>

But, they aren't reproducibly executed in that order. The cause is use of a set and not an ordered collection when caching the listeners in EntityManagerImpl#getEntityListeners(Object):

<pre>
				// if there are entity listeners, lets create them
				aListeners = new HashSet<Object>();
</pre>

**Comment by mhgrove** [comment]
yeah, good catch.  that should be `LinkedHashSet`
